name: youTubeWebApp
options:
  bundleIdPrefix: com.abhishek
  deploymentTarget:
    macOS: "13.0"
    visionOS: "2.0"
  createIntermediateGroups: true
targets:

  YouTubeVisionApp:
    type: application
    platform: visionOS
    sources:
      - path: visionOS
      - path: visionOS/Assets.xcassets
    entitlements:
      path: visionOS/YouTube.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abhishek.YouTube
        PRODUCT_NAME: YouTube
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: visionOS/Info.plist
        XROS_DEPLOYMENT_TARGET: "2.0"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: "YES"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: "YES"
        COMBINE_HIDPI_IMAGES: "YES"
        CLANG_ENABLE_MODULES: "YES"
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        GCC_OPTIMIZATION_LEVEL: "3"
        DEAD_CODE_STRIPPING: "YES"
    info:
      path: visionOS/Info.plist
      properties:
        CFBundleIconName: AppIcon
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconName: AppIcon 